create table if not exists public.investimentos_contas (
    id bigint generated by default as identity primary key,
    nome text not null,
    banco text not null,
    agencia text,
    conta text,
    descricao text,
    ativa boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.investimentos_aplicacoes (
    id bigint generated by default as identity primary key,
    conta_id bigint not null references public.investimentos_contas(id) on delete cascade,
    nome text not null,
    descricao text,
    percentual_juros_mensal numeric(10,6) not null default 0,
    base_dias text not null default 'corridos' check (base_dias in ('uteis', 'corridos')),
    rende_juros boolean not null default true,
    ativa boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.investimentos_movimentacoes (
    id bigint generated by default as identity primary key,
    conta_id bigint not null references public.investimentos_contas(id) on delete cascade,
    aplicacao_id bigint not null references public.investimentos_aplicacoes(id) on delete cascade,
    data_movimento date not null,
    tipo text not null check (tipo in ('aporte', 'resgate', 'ajuste', 'rendimento_manual')),
    descricao text not null,
    valor numeric(14,2) not null,
    observacao text,
    origem text not null default 'manual',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_investimentos_aplicacoes_conta_id
    on public.investimentos_aplicacoes(conta_id);

create index if not exists idx_investimentos_movimentacoes_aplicacao_data
    on public.investimentos_movimentacoes(aplicacao_id, data_movimento);

create index if not exists idx_investimentos_movimentacoes_conta_data
    on public.investimentos_movimentacoes(conta_id, data_movimento);
